### ISSUE TITLE
Issue in WPML translation

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/product-reviews-for-woocommerce#74]
Bug Name - Issue in WPML translation
Area Path - Backend
Woo Commerce Version - 5.6.0
WordPress Version - 5.8
Plugin Version - 1.0.2
Description - Paragraph in onboarding form is not translated
![wpml](https://user-images.githubusercontent.com/86114080/131286415-3233ee7d-e0fd-4369-b95e-058b4225bca2.png)

**Comment by sumitshukla-cedcoss** [comment]
Working fine

**Comment by Sukirti-CEDCOSS** [comment]
Verified
