### ISSUE TITLE
Issue in review submission in other language

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/product-reviews-for-woocommerce#75]
Bug Name - Issue in review submission in other language
Area Path - Frontend
Woo Commerce Version - 5.6.0
WordPress Version - 5.8
Plugin Version - 1.0.2
Description - In any other language when we submit review, "submitted successfully" pop-up is not displayed.

**Comment by sumitshukla-cedcoss** [comment]
Working fine

**Comment by Sukirti-CEDCOSS** [comment]
Verified
