### ISSUE TITLE
QA/PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/product-reviews-for-woocommerce#77]
DOC:
https://docs.google.com/document/d/1U0xWXHA9ac9X0aK1ZWmDqYHum_FvafHUoHhjm7XXbJQ/edit?usp=sharing

File:
[PHPcs..zip](https://github.com/Makewebbetter/product-reviews-for-woocommerce/files/7185146/PHPcs.zip)
[product-reviews-for-woocommerce.zip](https://github.com/Makewebbetter/product-reviews-for-woocommerce/files/7185147/product-reviews-for-woocommerce.zip)

**Comment by sumitshukla-cedcoss** [comment]
@Sukirti-CEDCOSS Issue Fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
